# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-09 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190909_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Holly Horwood', max_length=200),
            preserve_default=False,
        ),
    ]
