# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-14 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='county',
            new_name='region',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='ryan.connor@hotmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=70),
        ),
    ]
